# Generated by Django 5.1.6 on 2025-02-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produktkatalog",
            fields=[
                ("artikelNr", models.AutoField(primary_key=True, serialize=False)),
                ("artikel", models.CharField(max_length=50)),
                ("beschreibung", models.CharField(max_length=100)),
                ("preis", models.FloatField()),
            ],
        ),
    ]
