# Generated by Django 5.1.6 on 2025-02-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Produktkatalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produktkatalog",
            name="artikel",
            field=models.CharField(max_length=500),
        ),
    ]
