# Generated by Django 5.1.6 on 2025-02-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bestellungen",
            fields=[
                ("BestellNr", models.AutoField(primary_key=True, serialize=False)),
                ("BestellungAbgeschlossen", models.BooleanField()),
                ("Preis", models.FloatField()),
                ("KundenNummer", models.IntegerField()),
            ],
        ),
    ]
