# Generated by Django 5.1.6 on 2025-02-20 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Bestellungen", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bestellungen",
            old_name="BestellNr",
            new_name="bestellNr",
        ),
        migrations.RenameField(
            model_name="bestellungen",
            old_name="BestellungAbgeschlossen",
            new_name="bestellungAbgeschlossen",
        ),
        migrations.RenameField(
            model_name="bestellungen",
            old_name="KundenNummer",
            new_name="kundenNummer",
        ),
        migrations.RenameField(
            model_name="bestellungen",
            old_name="Preis",
            new_name="preis",
        ),
    ]
