# Generated by Django 5.1.6 on 2025-02-21 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bestellungen", "0002_rename_bestellnr_bestellungen_bestellnr_and_more"),
        ("Kunden", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bestellungen",
            name="kundenNummer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Kunden.kunden"
            ),
        ),
    ]
