# Generated by Django 5.1.6 on 2025-03-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bestellungen", "0003_alter_bestellungen_kundennummer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bestellungen",
            name="kundenNummer",
            field=models.CharField(max_length=50),
        ),
    ]
