# Generated by Django 5.1.6 on 2025-02-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mitarbeiter",
            fields=[
                ("mitarbeiterId", models.AutoField(primary_key=True, serialize=False)),
                ("nachname", models.CharField(max_length=50)),
                ("vorname", models.CharField(max_length=50)),
                ("strasse", models.CharField(max_length=50)),
                ("hausNr", models.CharField(max_length=50)),
                ("ort", models.CharField(max_length=50)),
                ("plz", models.IntegerField()),
                ("telefonNr", models.CharField(max_length=50)),
                ("gehalt", models.FloatField()),
                ("vertragSeit", models.DateField()),
                ("vertragBis", models.DateField()),
            ],
        ),
    ]
