# Generated by Django 5.1.6 on 2025-02-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kunden",
            fields=[
                ("kundenNummer", models.AutoField(primary_key=True, serialize=False)),
                ("vorname", models.CharField(max_length=50)),
                ("nachname", models.CharField(max_length=50)),
                ("strasse", models.CharField(max_length=50)),
                ("hausNr", models.CharField(max_length=50)),
                ("ort", models.CharField(max_length=50)),
                ("plz", models.IntegerField()),
                ("mailadresse", models.CharField(max_length=50)),
            ],
        ),
    ]
