# Generated by Django 5.1.6 on 2025-02-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bilanzdaten",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("umsatz", models.FloatField()),
                ("gewinn", models.FloatField()),
            ],
        ),
    ]
