# Generated by Django 5.1.6 on 2025-02-27 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Produktkatalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lagerbestand",
            fields=[
                ("artikelNr", models.AutoField(primary_key=True, serialize=False)),
                ("menge", models.IntegerField()),
                ("minBestand", models.IntegerField()),
                (
                    "artikel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Produktkatalog.produktkatalog",
                    ),
                ),
            ],
        ),
    ]
