# Generated by Django 5.1.6 on 2025-02-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Lagerbestand", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lagerbestand",
            name="artikel",
            field=models.CharField(max_length=50),
        ),
    ]
